name: Build iOS App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Retirer le code source
      uses: actions/checkout@v4

    - name: Configurer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install briefcase
        
    - name: Créer le projet Beeware / Application iOS
      run: |
        briefcase new --no-input
        mkdir -p "Rando Camara/src/randocamara"
        cp main.py "Rando Camara/src/randocamara/app.py"

    - name: Compiler l'application iOS
      run: |
        cd "Rando Camara"
        briefcase build ios
        briefcase package ios

    - name: Sauvegarder le fichier IPA
      uses: actions/upload-artifact@v4
      with:
        name: rando-camara-ipa
        path: "Rando Camara/macOS/ios/xcode/build/**/*.ipa"
